grafana.ini:
  server:
    domain: "${domain}"
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
  security:
    # cookie_secure: "true"
    # cookie_samesite: "strict"
    # login_cookie_name: "__Secure-grafana_session"
    # hide_version: "true"
    # enforce_domain: "true"
    content_security_policy: "true"
    content_security_policy_template: "\"\"\"default-src 'self'; script-src 'self' 'strict-dynamic' $NONCE; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval'; object-src 'none'; font-src 'self' https://fonts.gstatic.com/; img-src 'self'; style-src 'self' 'strict-dynamic' $NONCE; style-src-elem 'self' 'unsafe-inline' 'unsafe-eval'; base-uri 'self'; frame-ancestors 'none'; block-all-mixed-content;\"\"\""
