grafana.ini:
  server:
    domain: "${domain}"
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
  security:
    # cookie_secure: "true"
    # cookie_samesite: "strict"
    # login_cookie_name: "__Secure-grafana_session"
    # hide_version: "true"
    # enforce_domain: "true"
    content_security_policy: "true"
    content_security_policy_template: "\"\"\"default-src 'self'; script-src 'self' 'sha256-ayMoEtHnwKOlxYZlY9y4rLD1VTicVCESADY2I7OCKT4=' 'sha256-M8B9/WMwpruS+XKcXvUqd0A1mHnW61G4Q3YMW6dPLOo=' 'sha256-zgk5pdQDuTSdmqn198AwCD2RdnTnaFXOsFWr6ZsQTSQ=' 'sha256-kq0znwt6VSZC803XRbPGZcxaifxCSJ1BD+o5i2V0j9I=' 'sha256-4sCUpW5R4gW8wwcG/OBMON5SqA3IsSRb0vtjfChRtJw=' $NONCE; object-src 'none'; font-src 'self' https://fonts.gstatic.com/; img-src 'self'; style-src 'self' 'sha256-EwewAMFPXbWgXZ/3rpUubPFwOQX+c5UkobBr09ekAq0=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-1PxuDsPyGK6n+LZsMv0gG4lMX3i3XigG6h0CzPIjwrE=' $NONCE; base-uri 'self'; frame-ancestors 'none'; block-all-mixed-content;\"\"\""
